import { test } from "node:test";
import assert from "node:assert/strict";
import { friendlyModel, parseUsageLine, sourceOfPath, workingRoot } from "./usage-parse.ts";
import { OTHER_CWD, SCOPE_CWD, SENTINEL, assistantLine, source, userLine } from "./usage-fixtures.ts";

const AT = "2026-09-29T12:00:00.000Z";
const main = source("aaaa1111-0000-4000-8000-000000000001");
const parse = (line: string, repos: string[] = []) => parseUsageLine(line, main, { repos });
const request = (text: string, extra: Record<string, unknown> = {}) => parse(userLine({ at: AT, text, ...extra }))?.request;

test("a typed prompt is a human request, whatever shape its content has", () => {
  assert.equal(request("Pode ajustar o texto da tela inicial?"), "human");
  assert.equal(parse(userLine({ at: AT, content: [{ type: "text", text: "Pode ajustar?" }] }))?.request, "human");
  // A prompt that is only a pasted picture is still something the person did.
  assert.equal(parse(userLine({ at: AT, content: [{ type: "image", source: {} }] }))?.request, "human");
  assert.equal(parse(userLine({ at: AT, origin: { kind: "human" } }))?.request, "human");
});

test("a slash command is a command, not a human request", () => {
  assert.equal(request("<command-name>/clear</command-name>\n<command-message>clear</command-message>"), "command");
  assert.equal(request("  <command-message>compact</command-message>"), "command");
});

test("what the person did not type is automatic: summaries, task notices, system text", () => {
  const automatic = [
    "This session is being continued from a previous conversation that ran out of context.",
    "<task-notification><task-id>t1</task-id><status>completed</status></task-notification>",
    "<local-command-stdout>ok</local-command-stdout>",
    "<local-command-caveat>Caveat: the messages below were generated by the user</local-command-caveat>",
    "Caveat: the messages below were generated by the user while running local commands.",
    "<system-reminder>lembrete</system-reminder>",
    "[Request interrupted by user for tool use]",
    "<bash-input>ls</bash-input>",
    "<algum-bloco-xml>x</algum-bloco-xml>",
  ];
  for (const text of automatic) assert.equal(request(text), "automatic", text);
  // The flags the transcript itself sets count as much as the text does.
  assert.equal(request("resumo da conversa", { isCompactSummary: true }), "automatic");
  assert.equal(request("nota interna", { isMeta: true }), "automatic");
  assert.equal(request("aviso", { origin: { kind: "task-notification" } }), "automatic");
});

test("a user line that carries a tool result is not a request at all", () => {
  assert.equal(parse(userLine({ at: AT, toolResult: "saída do comando" }))?.request, "tool_result");
  assert.equal(
    parse(userLine({ at: AT, content: [{ type: "tool_result", content: "x" }, { type: "text", text: "e mais" }] }))?.request,
    "tool_result"
  );
});

test("an assistant line keeps the model, the ids and the four token counts", () => {
  const event = parse(
    assistantLine({ at: AT, model: "claude-sonnet-5-5", id: "msg_abc", requestId: "req_abc", usage: [3, 40, 500, 60] })
  );
  assert.ok(event);
  assert.equal(event.type, "assistant");
  assert.equal(event.at, Date.parse(AT));
  assert.equal(event.model, "claude-sonnet-5-5");
  assert.equal(event.messageId, "msg_abc");
  assert.equal(event.requestId, "req_abc");
  assert.deepEqual(event.usage, { input: 3, output: 40, cacheRead: 500, cacheWrite: 60 });
  assert.equal(event.request, null);
  assert.equal(event.source, main);
});

test("a line without ids or usage still yields an event, with zeros where the counts are missing", () => {
  const event = parse(assistantLine({ at: AT, id: null, requestId: null }));
  assert.ok(event);
  assert.equal(event.messageId, null);
  assert.equal(event.requestId, null);
  const bare = parse(JSON.stringify({ type: "assistant", timestamp: AT, message: { model: "claude-opus-5-5", content: [] } }));
  assert.deepEqual(bare?.usage, { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 });
  assert.equal(bare?.cwd, null);
});

test("a <synthetic> answer is kept as a line but carries no model usage to count", () => {
  const event = parse(assistantLine({ at: AT, model: "<synthetic>", usage: [9, 9, 9, 9] }));
  assert.ok(event);
  assert.equal(event.model, "<synthetic>");
  assert.equal(event.usage, null);
});

test("lines that are not messages, or are damaged, are skipped without throwing", () => {
  const damaged = [
    "",
    "   ",
    "not json at all",
    '{"type":"user","timestamp":"2026-09-2',
    "[]",
    "null",
    "42",
    '{"type":"summary","summary":"x"}',
    '{"type":"system","timestamp":"2026-09-29T12:00:00Z","content":"x"}',
    '{"type":"user"}',
    '{"type":"user","timestamp":"ontem"}',
    '{"type":"assistant","timestamp":null}',
    // Looks like a message to a plain text search, but the line itself is something else.
    '{"type":"system","timestamp":"2026-09-29T12:00:00Z","data":{"type":"user"}}',
  ];
  for (const line of damaged) assert.equal(parse(line), null, JSON.stringify(line));
});

test("the working directory is reduced to its root", () => {
  const deep = `${SCOPE_CWD}\\src\\${SENTINEL}\\components`;
  assert.equal(parse(userLine({ at: AT, cwd: deep }))?.cwd, SCOPE_CWD);
  assert.equal(workingRoot("C:\\Software\\GeoCloud\\GeoCloudAI"), "C:\\Software\\GeoCloud\\GeoCloudAI");
  assert.equal(
    workingRoot("C:\\Software\\GeoCloud\\GeoCloudAI\\.claude\\worktrees\\issue-12\\src"),
    "C:\\Software\\GeoCloud\\GeoCloudAI\\.claude\\worktrees\\issue-12"
  );
  assert.equal(workingRoot("c:/Software/RoadS/src/lib"), "c:\\Software\\RoadS");
  assert.equal(workingRoot("C:\\Software\\GeoCloud"), "C:\\Software\\GeoCloud");
  assert.equal(workingRoot("C:\\Users\\someone\\notes\\deep"), "C:\\Users\\someone");
});

test("a tool call keeps only the roots and watched repositories it points at", () => {
  const repo = "Essencis-Labs/GeoCloudAI";
  const event = parse(
    assistantLine({
      at: AT,
      tools: [
        { file_path: `${SCOPE_CWD}\\src\\${SENTINEL}\\a.ts` },
        { command: `cd /c/Software/RoadS && gh pr list --repo ${repo.toLowerCase()} && cat C:\\\\Software\\\\Elsewhere\\\\x.txt` },
        { command: `echo ${SENTINEL}` },
        { nested: { deeper: [`D:/Users/someone/${SENTINEL}/file.md`] } },
      ],
    }),
    [repo]
  );
  assert.ok(event);
  assert.deepEqual(event.tools, [
    { roots: ["C:/Software/GeoCloud/GeoCloudAI"], repos: [] },
    { roots: ["C:/Software/Elsewhere", "C:/Software/RoadS"], repos: [repo] },
    { roots: [], repos: [] },
    { roots: ["D:/Users/someone"], repos: [] },
  ]);
  // Without a watched repository the mention is not looked for.
  assert.deepEqual(parse(assistantLine({ at: AT, tools: [{ command: `gh --repo ${repo}` }] }))?.tools, [{ roots: [], repos: [] }]);
});

test("nothing the person or Claude wrote survives in the event", () => {
  const lines = [
    userLine({ at: AT, text: `Pedido com ${SENTINEL} dentro`, cwd: `${SCOPE_CWD}\\${SENTINEL}` }),
    userLine({ at: AT, toolResult: `saída ${SENTINEL}` }),
    userLine({ at: AT, content: [{ type: "text", text: SENTINEL }, { type: "image", source: { data: SENTINEL } }] }),
    assistantLine({
      at: AT,
      text: `resposta ${SENTINEL}`,
      cwd: `${OTHER_CWD}\\${SENTINEL}`,
      tools: [{ command: `rm -rf ${SENTINEL}`, file_path: `${SCOPE_CWD}\\${SENTINEL}\\x.ts`, content: SENTINEL }],
    }),
    JSON.stringify({
      type: "assistant",
      timestamp: AT,
      message: { id: "m", model: "claude-opus-5-5", content: [{ type: "thinking", thinking: SENTINEL }], usage: {} },
    }),
  ];
  for (const line of lines) {
    const event = parse(line, ["Essencis-Labs/GeoCloudAI"]);
    assert.ok(event, line.slice(0, 40));
    assert.ok(!JSON.stringify(event).includes(SENTINEL), "the event leaks text");
  }
});

test("a transcript path says which session it belongs to and what kind of file it is", () => {
  assert.deepEqual(sourceOfPath("C--Software-Demo/aaaa1111-0000.jsonl"), {
    project: "C--Software-Demo",
    session: "aaaa1111-0000",
    kind: "main",
  });
  // Windows separators too.
  assert.deepEqual(sourceOfPath("C--Software-Demo\\aaaa1111-0000.jsonl")?.kind, "main");
  assert.deepEqual(sourceOfPath("C--Software-Demo/aaaa1111-0000/subagents/agent-77.jsonl"), {
    project: "C--Software-Demo",
    session: "aaaa1111-0000",
    kind: "subagent",
  });
  assert.equal(sourceOfPath("C--Software-Demo/aaaa1111-0000/subagents/workflows/w1/agent-77.jsonl")?.kind, "workflow");
  for (const odd of ["aaaa1111.jsonl", "C--Software-Demo/aaaa1111.txt", "C--Software-Demo/aaaa1111/notes/other.jsonl", ""]) {
    assert.equal(sourceOfPath(odd), null, odd);
  }
});

test("model ids become the names people know", () => {
  assert.equal(friendlyModel("claude-opus-5-5"), "Opus 5.5");
  assert.equal(friendlyModel("claude-sonnet-5"), "Sonnet 5");
  assert.equal(friendlyModel("claude-fable-5-1"), "Fable 5.1");
  assert.equal(friendlyModel("claude-haiku-4-5-20251001"), "Haiku 4.5");
  assert.equal(friendlyModel("claude-opus-5-20260101"), "Opus 5");
  assert.equal(friendlyModel("claude-opus-5[1m]"), "Opus 5");
  assert.equal(friendlyModel("claude-3-5-sonnet-20241022"), "Sonnet 3.5");
  assert.equal(friendlyModel("some-other-model"), "some-other-model");
  assert.equal(friendlyModel(null), "Desconhecido");
  assert.equal(friendlyModel(""), "Desconhecido");
});
