-- Every Roadmap item is now a complete GeoCloud issue, status Open on Project #7 (#876–#916,
-- published 28/09 from the SCRUM/2026/ROADMAP.md text). This migration:
--   1. links the items RoadS already had to their new issue;
--   2. brings in the ROADMAP.md items RoadS didn't have yet, grouped by topic like the others,
--      plus two existing issues the ROADMAP points at (#222 rate limiting, #557 dormant modules);
--   3. queues each link ("modify") and each new item ("add") in roadmap_sync_queue, so the next
--      FrontlightS /update-roads writes the issue links into ROADMAP.md.
-- "CI com as quatro suítes" is left out: .github/workflows/ci.yml already runs all four suites on
-- every pull request.

-- 1. Links.
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/876', github_issue_number = 876, updated_at = now() where title = 'Sidebar recuado ao entrar em qualquer visualizador' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/877', github_issue_number = 877, updated_at = now() where title = 'Página própria do visualizador, com filtros de região até caixa' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/878', github_issue_number = 878, updated_at = now() where title = 'Título do nível corrido, com a data ao lado e a imagem do nível menor' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/879', github_issue_number = 879, updated_at = now() where title = 'Accordion do menu lateral direito: deixar explícito que abre listagem' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/880', github_issue_number = 880, updated_at = now() where title = 'Cota do topo do furo no Single View' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/881', github_issue_number = 881, updated_at = now() where title = 'Marcações em colunas verticais' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/882', github_issue_number = 882, updated_at = now() where title = 'Accordion por classe de geologia, com todos/desativar todos' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/883', github_issue_number = 883, updated_at = now() where title = 'Filtro para desligar classes de geologia por furo' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/884', github_issue_number = 884, updated_at = now() where title = 'Litologia metro a metro, normalizada' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/885', github_issue_number = 885, updated_at = now() where title = 'Coluna de geoquímica com gráfico e seleção do elemento' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/886', github_issue_number = 886, updated_at = now() where title = 'Coluna de mapa hiperespectral' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/889', github_issue_number = 889, updated_at = now() where title = 'Guias especializadas por classe de geologia no chat' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/892', github_issue_number = 892, updated_at = now() where title = 'Segmentação de testemunho na visão computacional' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/894', github_issue_number = 894, updated_at = now() where title = 'Sincronizar sample e resultados com o ELIMS' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/895', github_issue_number = 895, updated_at = now() where title = 'Tela de upload das informações de perfuração' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/898', github_issue_number = 898, updated_at = now() where title = 'Mapa básico com geolocalização de poços e furos' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/909', github_issue_number = 909, updated_at = now() where title = 'Escopo de empresa ao conceder acesso a projeto' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/910', github_issue_number = 910, updated_at = now() where title = 'Conversão de unidade de ensaio, hoje adivinhada' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/901', github_issue_number = 901, updated_at = now() where title = 'Dashboards avançados, com pedido à LLM' and github_issue_url is null;
update public.roadmap_items set github_issue_url = 'https://github.com/Essencis-Labs/GeoCloudAI/issues/902', github_issue_number = 902, updated_at = now() where title = 'Visualização 3D como módulo desligável' and github_issue_url is null;

insert into public.roadmap_sync_queue (item_id, action, payload)
select i.id, 'modify', jsonb_build_object('github_issue_url', i.github_issue_url, 'title', i.title, 'reason', 'issue linked')
from public.roadmap_items i
where i.github_issue_number between 876 and 916;

-- 2. New items. revisao-humana goes first in its group: it is the prerequisite of the whole AI block.
update public.roadmap_items set sort_order = sort_order + 1 where lane_id = 'g2';
insert into public.roadmap_items
  (lane_id, sort_order, title, description, produto, prioridade, effort, github_issue_url, github_issue_number)
values
  ('g1', 10, 'Colunas de FRX e magnetometria no Single View', 'Anotações de 08/09, lote do Single View com colunas de dados, parte com bloqueio (sem data). O Single View deve mostrar as leituras de FRX (fluorescência de raios X) e de magnetometria por profundidade, como duas curvas ao lado do testemunho. A versão mockada…', 'GeoCloud', 'Low', 'Medium', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/887', 887),
  ('g2', 0, 'Revisão humana obrigatória antes de detecção automática virar dado oficial', 'Pré-requisito de todo o bloco de IA, relatórios e visão computacional (Sprints 8 e 9 do ROADMAP). Hoje não existe revisão humana antes de uma detecção automática virar dado oficial, e esse é o único controle que falta na visão computacional. Sem ele, a…', 'GeoCloud', 'High', 'Low', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/888', 888),
  ('g2', 10, 'Reformular o design do chat e a formatação dos relatórios', 'Anotações de 08/09, bloco de IA e relatórios (Sprint 8, 2,0 dias). O chat e os relatórios que ele gera precisam de um design novo: hoje o texto sai com formatação irregular e a tela não segue o padrão visual do resto do produto.', 'GeoCloud', 'Medium', 'Medium', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/890', 890),
  ('g2', 11, 'Relatórios sem passar pelo chat, com texto editável', 'Anotações de 08/09, bloco de IA e relatórios (Sprint 8, 2,5 dias). Hoje o relatório só nasce de uma conversa no chat. O usuário quer gerar o relatório direto, a partir do furo ou da caixa, e editar o texto antes de exportar.', 'GeoCloud', 'Medium', 'Medium', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/891', 891),
  ('g2', 12, 'Notificação de incoerência entre análise visual da IA e marcações', 'Anotações de 08/09, bloco de visão computacional (Sprint 9, 3,0 dias). Quando a análise visual da IA discorda da marcação do geólogo (por exemplo, a IA vê fratura onde não há marcação, ou litologia diferente), o sistema deve notificar e propor a correção no…', 'GeoCloud', 'Medium', 'High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/893', 893),
  ('g3', 10, 'Importação de dados da empresa cliente', 'Anotações de 08/09, bloco de dados, mapas e importação (3,0 dias). O cliente chega com anos de dado de exploração em outros sistemas e planilhas; sem importação, o GeoCloud começa vazio e a adoção trava.', 'GeoCloud', 'Medium', 'High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/896', 896),
  ('g3', 11, 'Inputar os dados da Vale e da EuroCore', 'Anotações de 08/09, bloco de dados, mapas e importação. Entra assim que os arquivos chegarem; o esforço vai de 1,0 a 4,0 dias e muda por completo com o formato. É o que dá dado real para as colunas do Single View e para as demonstrações.', 'GeoCloud', 'Medium', 'Medium', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/897', 897),
  ('g3', 12, 'Armazenar e visualizar mapas hiperespectrais', 'Anotações de 08/09, bloco de dados, mapas e importação (4,0 dias). O GeoCloud não guarda mapas hiperespectrais hoje. Este item precede a coluna hiperespectral do Single View e é base para o módulo de análise complexa.', 'GeoCloud', 'Low', 'High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/899', 899),
  ('g3', 13, 'Mapa avançado com cruzamento de dados e Geomind', 'Anotações de 08/09, bloco de dados, mapas e importação (6,0 dias ou mais). Evolução do mapa básico: cruzar no mapa os dados do cliente (furos, teores, litologia) com dados públicos centralizados pelo Geomind.', 'GeoCloud', 'Low', 'Very High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/900', 900),
  ('g5', 10, 'Visualização do testemunho em 3D', 'Módulos futuros do ROADMAP (12,0 dias). Mostrar o próprio testemunho em 3D — o cilindro com a imagem da caixa aplicada, ao longo da trajetória do furo. Candidato a módulo pago.', 'GeoCloud', 'Low', 'Very High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/903', 903),
  ('g5', 11, 'GeoCloud LIMS Laboratório: análise complexa (escopo a definir com o João)', 'Módulos futuros do ROADMAP, sem estimativa. Análise complexa de laboratório: hiperespectral, cubo de dados e geoquímica, com gráfico por pixel da imagem. As anotações registram que o escopo não ficou claro, e é preciso uma conversa com o João antes de…', 'GeoCloud', 'Low', 'Very High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/904', 904),
  ('g5', 12, 'ELIMS/LM avançado dentro do GeoCloud', 'Módulos futuros do ROADMAP, sem estimativa. Trazer para dentro do GeoCloud as informações das amostras do ELIMS/LM de forma avançada — além da sincronização básica de sample e resultados (item 5 do João).', 'GeoCloud', 'Low', 'High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/905', 905),
  ('g5', 13, 'Geomind: centralização de dados públicos (terras raras, geoquímicos, hiperespectrais)', 'Módulos futuros do ROADMAP (10,0 dias ou mais). Centralizar dados públicos de terras raras, geoquímicos e hiperespectrais, com apoio de LLM externa. É o que alimenta o mapa avançado.', 'GeoCloud', 'Low', 'Very High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/906', 906),
  ('g5', 14, 'Treinamento de redes neurais dentro do produto (portar do Orange)', 'Módulos futuros do ROADMAP, sem estimativa. O João criou fluxos de treinamento de redes neurais no Orange; o trabalho é portá-los para dentro do produto.', 'GeoCloud', 'Low', 'High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/907', 907),
  ('g4', 10, 'Financeiro particionado por empresa, com reatribuição dos lançamentos', 'Dívida técnica da lista de sugestão apresentada na reunião de 08/09 (2,0 dias). A recomendação era fazer cedo: custa pouco agora e caro depois do primeiro cliente com um ano de lançamentos.', 'GeoCloud', 'Medium', 'Medium', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/908', 908),
  ('g4', 11, 'Trajetória do furo por desvio, hoje uma reta', 'Dívida técnica da lista de sugestão apresentada na reunião de 08/09 (3,0 dias). Recomendação: fazer antes de qualquer entrega de 3D, que herda a geometria errada. O ROADMAP destaca este item porque contamina módulos futuros: a visualização 3D e o testemunho…', 'GeoCloud', 'Medium', 'High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/911', 911),
  ('g4', 12, 'Histórico de anotação geológica, hoje sobrescrito junto do autor', 'Dívida técnica da lista de sugestão apresentada na reunião de 08/09 (1,5 dia). Recomendação: fazer antes de auditoria de recurso mineral. O ROADMAP destaca este item porque contamina módulos futuros: o LIMS de laboratório construído sobre anotação sem…', 'GeoCloud', 'Medium', 'Medium', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/912', 912),
  ('g6', 0, 'Core gratuito com defasagens frente aos módulos pagos', 'Decisão de 21/09, nascida do planejamento do gateway de pagamentos (#715): o Core continua gratuito, mas passa a ter defasagens frente aos módulos pagos — por exemplo, imagens estáticas de testemunho em vez do visualizador avançado (KoreGeo3, Multi View,…', 'GeoCloud', 'High', 'Medium', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/913', 913),
  ('g6', 1, 'Fichar Imago, Plexer e Datamine Fusion na matriz de concorrentes', 'Anotação do ROADMAP sobre a comparação entre EuroCore e GeoCloud. A EuroCore é referência de modelo de dados, não concorrente; a comparação de produto que importa é GeoCloud contra Imago, que o João cita duas vezes como referência de interface. E o Imago não…', 'GeoCloud', 'Low', 'Low', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/914', 914),
  ('g6', 2, 'Esconder botões e ações nas telas conforme as funcionalidades do usuário', 'Continuação da #871, pedido do Scrum Master Luiz Damore em 28/09. A #871 entrega o endpoint com as permissões e os módulos efetivos do usuário, o menu montado a partir dele e o guard de rota. Esconder botões e ações dentro de cada tela ficou de fora de…', 'GeoCloud', 'Medium', 'High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/915', 915),
  ('g6', 3, 'Padronizar a interface do GeoCloud contra o ELIMS (começa pela auditoria tela a tela)', 'Item 2 do João. O Sprint 2 previa só a auditoria: percorrer tela por tela, listar cada divergência de padrão contra o ELIMS e estimar cada uma. A padronização em si é trabalho de vários sprints e não deve começar sem essa lista, sob risco de padronizar o que…', 'GeoCloud', 'Low', 'High', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/916', 916),
  ('g4', 13, 'Limite de requisição por origem e auditoria das chamadas', 'Dívida técnica da reunião de 08/09, para entrar junto do gateway de pagamentos. A limitação por IP que existia foi retirada do código; a issue #222 cobre a reimplementação.', 'GeoCloud', 'Medium', 'Medium', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/222', 222),
  ('g4', 14, 'Logística, Painel Operacional e Financeiro: decidir o futuro dos módulos dormentes', 'Cobre, pela #557, três itens do ROADMAP: Logística autenticada e escopada, Painel Operacional autenticado, e o Financeiro/Logística a partir do CorePlan. Os três saíram do MVP em 10/09; a segurança já foi tratada na #498.', 'GeoCloud', 'Medium', 'Medium', 'https://github.com/Essencis-Labs/GeoCloudAI/issues/557', 557);

insert into public.roadmap_sync_queue (item_id, action, payload)
select i.id, 'add', jsonb_build_object('lane_id', i.lane_id, 'title', i.title, 'github_issue_url', i.github_issue_url)
from public.roadmap_items i
where i.created_at >= now() - interval '1 minute'
  and i.created_by is null
  and not exists (select 1 from public.roadmap_sync_queue q where q.item_id = i.id);
